/* ************************************************************************ */
/*         Queries to get counts of null values by each column              */
/* ************************************************************************ */

/* ----------------- Teranet dataset with added columns ------------------- */

SELECT SUM(CASE WHEN transaction_id IS NULL THEN 1 ELSE 0 END) AS transaction_id_c,
       SUM(CASE WHEN lro_num IS NULL THEN 1 ELSE 0 END) AS lro_num_c,
       SUM(CASE WHEN pin IS NULL THEN 1 ELSE 0 END) AS pin_c,
       SUM(CASE WHEN consideration_amt IS NULL THEN 1 ELSE 0 END) AS consideration_amt_c,
       SUM(CASE WHEN registration_date IS NULL THEN 1 ELSE 0 END) AS registration_date_c,
       SUM(CASE WHEN postal_code IS NULL THEN 1 ELSE 0 END) AS postal_code_c,
       SUM(CASE WHEN unitno IS NULL THEN 1 ELSE 0 END) AS untino_c,
       SUM(CASE WHEN street_name IS NULL THEN 1 ELSE 0 END) AS street_name_c,
       SUM(CASE WHEN street_designation IS NULL THEN 1 ELSE 0 END) AS street_designation_c,
       SUM(CASE WHEN street_direction IS NULL THEN 1 ELSE 0 END) AS street_direction_c,
       SUM(CASE WHEN municipality IS NULL THEN 1 ELSE 0 END) AS municipality_c,
       SUM(CASE WHEN street_number IS NULL THEN 1 ELSE 0 END) AS street_number_c,
       SUM(CASE WHEN x IS NULL THEN 1 ELSE 0 END) AS x_c,
       SUM(CASE WHEN y IS NULL THEN 1 ELSE 0 END) AS y_c,
       SUM(CASE WHEN objectid IS NULL THEN 1 ELSE 0 END) AS objectid_c,
       SUM(CASE WHEN dauid IS NULL THEN 1 ELSE 0 END) AS dauid_c,
       SUM(CASE WHEN csdname IS NULL THEN 1 ELSE 0 END) AS csdname_c,
       SUM(CASE WHEN street_name_raw IS NULL THEN 1 ELSE 0 END) AS street_name_raw_c,
       SUM(CASE WHEN date_disp IS NULL THEN 1 ELSE 0 END) AS date_disp_c,
       SUM(CASE WHEN price_disp IS NULL THEN 1 ELSE 0 END) AS price_disp_c,
       SUM(CASE WHEN year IS NULL THEN 1 ELSE 0 END) AS year_c,
       SUM(CASE WHEN year3 IS NULL THEN 1 ELSE 0 END) AS year3_c,
       SUM(CASE WHEN year5 IS NULL THEN 1 ELSE 0 END) AS year5_c,
       SUM(CASE WHEN year10 IS NULL THEN 1 ELSE 0 END) AS year10_c,
       SUM(CASE WHEN xy IS NULL THEN 1 ELSE 0 END) AS xy_c,
       SUM(CASE WHEN pin_total_sales IS NULL THEN 1 ELSE 0 END) AS pin_total_sales_c,
       SUM(CASE WHEN xy_total_sales IS NULL THEN 1 ELSE 0 END) AS xy_total_sales_c,
       SUM(CASE WHEN pin_prev_sales IS NULL THEN 1 ELSE 0 END) AS pin_prev_sales_c,
       SUM(CASE WHEN xy_prev_sales IS NULL THEN 1 ELSE 0 END) AS xy_prev_sales_c,
       SUM(CASE WHEN pin_price_cum_sum IS NULL THEN 1 ELSE 0 END) AS pin_price_cum_sum_c,
       SUM(CASE WHEN xy_price_cum_sum IS NULL THEN 1 ELSE 0 END) AS xy_price_cum_sum_c,
       SUM(CASE WHEN pin_price_pct_change IS NULL THEN 1 ELSE 0 END) AS pin_price_pct_change_c,
       SUM(CASE WHEN xy_price_pct_change IS NULL THEN 1 ELSE 0 END) AS xy_price_pct_change_c,
       SUM(CASE WHEN price_da_pct_change IS NULL THEN 1 ELSE 0 END) AS price_da_pct_change_c,
       SUM(CASE WHEN pin_years_since_last_sale IS NULL THEN 1 ELSE 0 END) AS pin_year_since_last_sale_c,
       SUM(CASE WHEN xy_years_since_last_sale IS NULL THEN 1 ELSE 0 END) AS xy_years_since_list_sale_c,
       SUM(CASE WHEN da_days_since_last_sale IS NULL THEN 1 ELSE 0 END) AS da_days_since_last_sale_c,
       SUM(CASE WHEN da_years_since_last_sale IS NULL THEN 1 ELSE 0 END) AS da_years_since_last_sale_c,
       SUM(CASE WHEN pin_sale_next_6m IS NULL THEN 1 ELSE 0 END) AS pin_sale_next_6m_c,
       SUM(CASE WHEN pin_sale_next_1y IS NULL THEN 1 ELSE 0 END) AS pin_sale_next_1y_c,
       SUM(CASE WHEN pin_sale_next_3y IS NULL THEN 1 ELSE 0 END) AS pin_sale_next_3y_c,
       SUM(CASE WHEN xy_sale_next_6m IS NULL THEN 1 ELSE 0 END) AS xy_sale_next_6m_c,
       SUM(CASE WHEN xy_sale_next_1y IS NULL THEN 1 ELSE 0 END) AS xy_sale_next_1y_c,
       SUM(CASE WHEN xy_sale_next_3y IS NULL THEN 1 ELSE 0 END) AS xy_sale_next_3y_c
FROM teranet;

/* ************************************************************************ */
/*       Queries to get percentages of non-null values by each column       */
/* ************************************************************************ */

/* ----------------- Teranet dataset with added columns ------------------- */

SELECT 100.0 * SUM(CASE WHEN transaction_id IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS transaction_id_p,
       100.0 * SUM(CASE WHEN lro_num IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS lro_num_p,
       100.0 * SUM(CASE WHEN pin IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS pin_p,
       100.0 * SUM(CASE WHEN consideration_amt IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS consideration_amt_p,
       100.0 * SUM(CASE WHEN registration_date IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS registration_date_p,
       100.0 * SUM(CASE WHEN postal_code IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS postal_code_p,
       100.0 * SUM(CASE WHEN unitno IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS untino_p,
       100.0 * SUM(CASE WHEN street_name IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS street_name_p,
       100.0 * SUM(CASE WHEN street_designation IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS street_designation_p,
       100.0 * SUM(CASE WHEN street_direction IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS street_direction_p,
       100.0 * SUM(CASE WHEN municipality IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS municipality_p,
       100.0 * SUM(CASE WHEN street_number IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS street_number_p,
       100.0 * SUM(CASE WHEN x IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS x_p,
       100.0 * SUM(CASE WHEN y IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS y_p,
       100.0 * SUM(CASE WHEN objectid IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS objectid_p,
       100.0 * SUM(CASE WHEN dauid IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS dauid_p,
       100.0 * SUM(CASE WHEN csdname IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS csdname_p,
       100.0 * SUM(CASE WHEN street_name_raw IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS street_name_raw_p,
       100.0 * SUM(CASE WHEN date_disp IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS date_disp_p,
       100.0 * SUM(CASE WHEN price_disp IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS price_disp_p,
       100.0 * SUM(CASE WHEN year IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS year_p,
       100.0 * SUM(CASE WHEN year3 IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS year3_p,
       100.0 * SUM(CASE WHEN year5 IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS year5_p,
       100.0 * SUM(CASE WHEN year10 IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS year10_p,
       100.0 * SUM(CASE WHEN xy IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS xy_p,
       100.0 * SUM(CASE WHEN pin_total_sales IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS pin_total_sales_p,
       100.0 * SUM(CASE WHEN xy_total_sales IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS xy_total_sales_p,
       100.0 * SUM(CASE WHEN pin_prev_sales IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS pin_prev_sales_p,
       100.0 * SUM(CASE WHEN xy_prev_sales IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS xy_prev_sales_p,
       100.0 * SUM(CASE WHEN pin_price_cum_sum IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS pin_price_cum_sum_p,
       100.0 * SUM(CASE WHEN xy_price_cum_sum IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS xy_price_cum_sum_p,
       100.0 * SUM(CASE WHEN pin_price_pct_change IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS pin_price_pct_change_p,
       100.0 * SUM(CASE WHEN xy_price_pct_change IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS xy_price_pct_change_p,
       100.0 * SUM(CASE WHEN price_da_pct_change IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS price_da_pct_change_p,
       100.0 * SUM(CASE WHEN pin_years_since_last_sale IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS pin_year_since_last_sale_p,
       100.0 * SUM(CASE WHEN xy_years_since_last_sale IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS xy_years_since_list_sale_p,
       100.0 * SUM(CASE WHEN da_days_since_last_sale IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS da_days_since_last_sale_p,
       100.0 * SUM(CASE WHEN da_years_since_last_sale IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS da_years_since_last_sale_p,
       100.0 * SUM(CASE WHEN pin_sale_next_6m IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS pin_sale_next_6m_p,
       100.0 * SUM(CASE WHEN pin_sale_next_1y IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS pin_sale_next_1y_p,
       100.0 * SUM(CASE WHEN pin_sale_next_3y IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS pin_sale_next_3y_p,
       100.0 * SUM(CASE WHEN xy_sale_next_6m IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS xy_sale_next_6m_p,
       100.0 * SUM(CASE WHEN xy_sale_next_1y IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS xy_sale_next_1y_p,
       100.0 * SUM(CASE WHEN xy_sale_next_3y IS NULL THEN 1 ELSE 0 END) / COUNT(*) AS xy_sale_next_3y_p
FROM teranet;
